---
- name: Install and configure LAMP stack
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache
      apt:
        name: apache2
        state: latest

    - name: Install MySQL
      apt:
        name: mysql-server
        state: latest

    - name: Install PHP and related modules
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - php
        - libapache2-mod-php
        - php-mysql

    - name: Configure Apache
      template:
        src: apache.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf
      notify: restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
